# Define the build job as an anchor
.build_job_definition: &build_job_definition
  name: Build
  runs-on: ubuntu-latest
  
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: echo "Deploying to production"
