
# Define the build job as an anchor
.build_job_definition: &build_job_definitionv
  name: Test
  runs-on: ubuntu-latest
  
  steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: echo "Deploying to production"
