name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Backend tests
        run: npm test
        working-directory: ./backend

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend tests
        run: npm test
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./backend   # Set the default working directory for the entire job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        # Add your deployment steps here
        run: echo "Deploying to production"
