name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Use the anchor for the build job
      - <<: *build_job_definition

# Define the build job as an anchor
.build_job_definition: &build_job_definition
  name: Build
  run: echo "Replace this with your actual build steps"
